server:
  port: 0
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true
    lease-renewal-interval-in-seconds: 30
spring:
  application:
    name: client-service
    instance_id: 2
logging:
  level:
    com.example.clientservice.controllers.ClientBookController: DEBUG