server:
  port: 0
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true
    lease-renewal-interval-in-seconds: 30
spring:
  data:
      mongodb:
        host: localhost                 # ????, ?? ??????? ???????? MongoDB
        port: 27017                    # ???? MongoDB
        database: bookbase           # ??? ???? ??????, ? ??????? ?? ?????? ????????????
  application:
    name: book-service
  cloud:
    config:
      import-check:
        enabled: false
